### ISSUE TITLE
Retrieve Commit Hash

### ISSUE THREAD

**Issue by jnovack** [ianstormtaylor/download-github-repo#5]
Would it be fruitful to retrieve the commit hash both as a separate call (`.getCommit()`, and returned as part of the callback?

It could prevent multiple downloads when the commit has not changed.

**Comment by ianstormtaylor** [comment]
Not sure exactly what you mean, but open to it.

**Comment by jnovack** [comment]
Currently, you download the `master.zip`, but unless I track the second I send you the call and get the callback, I have no idea which commit I just pulled (I may have pulled a bad one).

I feel that at least returning the commit hash in the callback (or making a separate call retrieve the commit hash, beware of race conditions), would help IMMENSELY.

As examples:
* I might want a button in my application that checks for updates, without actually downloading the repo.
* I might want to poll for updates and only update (download the zip) if the hash has changed.
* I might want to prevent multiple zip downloads every time the download function is run by checking against the hash.

**Comment by jnovack** [comment]
I think the proper way to do it (to avoid race conditions), would be to:

* Get the commit hash of master - https://api.github.com/repos/:owner/:repo/commits/master
* Download the commit hash - https://github.com/:owner/:repo/archive/:commit.zip

**Comment by jnovack** [comment]
Continuing with the "best way to do it"(tm) to avoid race conditions, idea; we should be returning promises.

Considering that 0.10 support is going away, and while 0.12 is LTS, the amount of ES6 features it has is low, **are you willing to version bump this package, AND minimum require node v4.0**?

A refactoring is necessary to provide two functions (since it only exports `download()`), thus if you are going to refactor, my thought would be to bring it up-to-date(tm) with ES6.

**Comment by ianstormtaylor** [comment]
Hey, just saw this. Makes sense about wanting to track a specific commit hash instead of a branch or tag. I think the code as currently architected actually already supports this by doing:

```js
download('owner/repo#commit', ...
```

Where `commit` is the hash, instead of a branch or tag name.

At that point, it seems like all of the other logic around determining whether the file should be re-downloaded or not could live outside this package, and be tweaked however you want.

Does that make sense, or am I missing something?

(Unrelated, happy to accept a major version bump that swaps callbacks for promises, and requires node `4.0` or higher.)

**Comment by jnovack** [comment]
Yes, I think I'm not explaining my use case correctly.  Here's an example.

My parent application is an automated downloader, that downloads the repo at midnight.  So every night, I run `download('owner/repo'...` (because I want the latest), BUT, I don't want to waste my time downloading if it was the same last night --OR-- I don't want to waste my time processing the repo (doing whatever I do with it) because it was the same last night.

My branch solves either of those problems.   By adding `query()` and returning the hash from `download()`, the parent application can SKIP the `download()` AND/OR SKIP the post-download processing if the hash was the same.

**Comment by ianstormtaylor** [comment]
Wouldn't you be able to solve that by having the parent application lookup the latest commit on master with GitHub's API, and then always invoking `download()` with the commit syntax, and choosing not to invoke if the commit hasn't changed?

**Comment by jnovack** [comment]
Yes, but why do the lookups in the parent application when the package is just one function away from doing it for all parent applications that want to do it?

**Comment by ianstormtaylor** [comment]
Because it adds a complication to the API that doesn't really seem necessary, since this package is only concerned with downloading a specific zip for a repository, not figuring out which commits people want or deciding not to download or whatever.

**Comment by jnovack** [comment]
Fair enough.

**Comment by ianstormtaylor** [comment]
Thanks man, thanks for the discussion in the first place.
